language: java
jdk: openjdk8

env:
  global:
  - secure: GDG2FaLyWyO2flJH00MhppLFCRxGk/2nzY2VoYLcGSCNGjT5ZKZpT474AnJGsiLvjSZBvFK1wB8WW9BEnlCUDzUS5UzhUnJBz+SMgaz1m67SyPkm8fjr2MGkakrBtkKiyMZ94MlOUT9i6DMIK/RJPMS40W96ELRZ1SImylq6CIF/2miwogASZNKIXvEOq2JfL1+W3KmqLixSTtE8ig1k0POq8z30ruxnn2gO6UniOhtAmdf4WIsBj3FkErR9PEkFHIlUEg1VxIoMqWm7/BWkRoj+44TENG7I5l28v+46zwK3Ve4fNBoZyI4BZPHIzAbiOHD1kn+aAk2vb84jJxve/wic7DqCpBHCP7qYNk7r126SvMxERu7k+HB2/B7sqx1tZWFeA+W+wCZRV7TqrQnfRTSf39tQioBPW7OEj3I4azUBNSKE4Rlp9O14/P0zm0ob3kWIsWAZQ169pZOPRmOm8tY07bcytcq/t23/eBRPUXl074rA4oe4jeITWiJ9J3LBXBDU7jXXKqdB+1ppHxfdVRftjLRgQnKHJwSalkvpdtHUTMWnGFk+U6IAK1LXkW6PUZEh5a51foWXDzt0Fvn5x1SZfIegT8jrzvjIDNz0TbGsdwFQDmi/AZMdhQlx52IpJJUUpk4HEFQB0RmRwR1YOLmWY80q35SU+YrNDxkhnpw=
  - secure: h+T93mTFC/BOxlics0EoeiIeDng7V/pgyfMN34rs017yNif4w5VXaE+YZe5k6+PwXBahkRwiiwo60m1cdN8tjefYCwX4wAwaSSX26dFKEcXPet+KYy3F4YLFyF1cNjFZUD65vC2CHQbLUiNG4jFMKjFpB10DIxItitmRBlrgiVSEvDlpWNfz66UujxmTBG/l7muqriGN4O2caWvuRb0v/Cm0HNjfoAMMK7AnrfF55CX3PiyQfNvmnqA9U9cUXYXRkIO5OEatOBhby+TqxM9+A3JIs0+QgxvCwJMoW1KXh5xqiYGmOwQrZdrsx+sz708EkrDnkvRPH56SodwO3/p65oBK1xSX7DEBVAiLy1oB7bDHOTWfnmbw2pCFXmuup6xh6HxUBVKWjenmwwgx4qckxoiuOu5T17aTwYIZBHyvEB1aYX9HwV9UYe7uaAkc23eUWLXH97/G2p0Jm4EuL5hZbd8JfL84cD8uQk3pBlug2Rrj4lfvTx2cZKY5nupeFMQqYEnWz9ADYArwAWfEOe1bMVVaHx3e3lwJYB95t3EuvzFZI1esIIzxmlZnoGX/7QqgLdHg1QCqBhAJ4UAjW5K8GGuUquikM/I7HGLZrs8AgKG75xjaxFPL8nFIXjIxpniml+XPrCYD8jotJ3enrxXu/8DW/lXJmdnNPbZ2i/s63H0=

addons:
  sonarcloud:
    organization: jensim-github
    token:
      secure: l88epfLiXnoQg8k/PSmFG/oI3XGdjs/HqW7ZXrWi4oXr5QWZI3ywVvCDTae+pjPxMBkg5vSLmJpADxCrYgTTMA7cjbcmFekcNL6dDd1DUq2R0FrEzYNUE8s/9x1aCzR7FST0sEalL8ZO12zRHOQvivVx6iyELaQOSLUecStdmSE2QTFkOsNmtsP+OEWzw5fJ5kSke48eD8RhCa5of7eLEfEbNjD/yqF6tSn6vvaV7XiCX9pK8V89nK7BJLMGWxfj9CcjnMFkvlUebfukxM8OtDRkGCAA7170eNEiaWbNAnbjfyP9GIkDgbXG3jWCJ8nPPH1G7dmd9gciMpicxtGvh7dlCXjcurrMoz19RW41O8QK1/T9n6t74npZ0hauUhavJGeqgNVJCIGXUCoctvjSUH0CCVP+yO/za/P5bLAsbwsMmEslvIrRzxAScF8IzfnfJlnfg6B9R/pTYjJ+1jPBJ4CG+Zf4IQF7yOXvZOh9Bl0GcjtO7S2aPjOtI1DszhFNVOwRWJon/ZdfxNvgepFI4ViE35rDSKkOz09W4zzd73dV66zUriSTJGmModRTfI8dU3+EebyI96C3NuWUR2Fds8aRfSqd/ghCQfBg9DPC1TnbEqV3fZGf3JQYnCR88tT9NDpVigKrrAFYG1vmpS0MBb70pkKF7PWSjomr6jRU9xQ=
jobs:
  include:
  - stage: Build and test
    script:
     - "./gradlew build jacocoTestReport sonarqube publish --stacktrace"
     - "cd example"
     - "./gradlew -b dev.build.gradle.kts build --stacktrace"
    if: tag IS blank
  - stage: Publish to gradle portal
    script:
     - "./gradlew build publish --stacktrace"
     - "cd example"
     - "./gradlew -b dev.build.gradle.kts build --stacktrace"
     - "cd .."
     - "./gradlew publishPlugins -PreleaseVersion=$TRAVIS_TAG -Pgradle.publish.key=$APIKEY -Pgradle.publish.secret=$APISECRET --stacktrace"
    if: tag IS present
